export const MOCK_CAR_DATA = {
  "Toyota": ["Camry", "Corolla", "RAV4", "Land Cruiser", "Hilux", "Fortuner", "Yaris", "Supra", "Prius", "Tacoma", "Tundra"],
  "Honda": ["Civic", "Accord", "CR-V", "City", "Amaze", "HR-V", "Jazz", "NSX", "Pilot", "Odyssey"],
  "Ford": ["F-150", "Mustang", "Explorer", "Endeavour", "EcoSport", "Ranger", "Bronco", "Edge", "Expedition"],
  "Tesla": ["Model S", "Model 3", "Model X", "Model Y", "Cybertruck", "Roadster"],
  "Tata": ["Nexon", "Punch", "Harrier", "Safari", "Tiago", "Altroz", "Tigor", "Curvv"],
  "Hyundai": ["Creta", "i20", "Verna", "Tucson", "Venue", "Elantra", "Alcazar", "Kona", "Ioniq 5"],
  "Mahindra": ["Thar", "Scorpio-N", "XUV700", "Bolero", "XUV300", "Scorpio Classic", "Marazzo"],
  "BMW": ["3 Series", "5 Series", "7 Series", "X1", "X3", "X5", "X7", "M3", "M4", "M5", "Z4", "i7"],
  "Mercedes-Benz": ["A-Class", "C-Class", "E-Class", "S-Class", "GLA", "GLC", "GLE", "GLS", "G-Wagon", "EQS", "AMG GT"],
  "Audi": ["A4", "A6", "A8", "Q3", "Q5", "Q7", "Q8", "e-tron", "RS5", "RSQ8", "R8"],
  "Kia": ["Seltos", "Sonet", "Carens", "EV6", "Carnival", "Sportage", "Sorento", "Telluride"],
  "Volkswagen": ["Virtus", "Taigun", "Polo", "Tiguan", "Golf", "Jetta", "Passat", "ID.4"],
  "Suzuki": ["Swift", "Baleno", "Brezza", "Ertiga", "Jimny", "Grand Vitara", "Alto", "WagonR", "Ciaz"],
  "Nissan": ["Magnite", "GT-R", "Altima", "Sentra", "Rogue", "Pathfinder", "Patrol", "Z", "Leaf"],
  "Lexus": ["IS", "ES", "LS", "NX", "RX", "GX", "LX", "LC"],
  "Porsche": ["911", "718 Cayman", "Taycan", "Panamera", "Macan", "Cayenne"],
  "Land Rover": ["Defender", "Discovery", "Range Rover", "Range Rover Sport", "Velar", "Evoque"],
  "Jeep": ["Compass", "Meridian", "Wrangler", "Grand Cherokee", "Gladiator"],
  "Lamborghini": ["Aventador", "Huracan", "Urus", "Revuelto"],
  "Ferrari": ["296 GTB", "F8", "Roma", "812 Superfast", "Purosangue", "SF90"],
  "Volvo": ["S60", "S90", "XC40", "XC60", "XC90", "C40 Recharge"],
  "Jaguar": ["XE", "XF", "XJ", "F-Pace", "E-Pace", "I-Pace"],
  "Maserati": ["Ghibli", "Quattroporte", "Levante", "MC20"],
  "Bentley": ["Continental GT", "Flying Spur", "Bentayga"]
};